### ISSUE TITLE
Update the output file names

### ISSUE THREAD

**Issue by ingeniumed** [Automattic/vip-design-system-bridge#22]
This is meant to implement an output system that based on what's being outputted to, would change the name of the file. 

Output: Wordpress

output -> theme.json (token-transformer and SD)
provide -> theme to use or the source/layer sets

Output: React

output -> react.json (token-transformer only)
provide -> theme to use or the source/layer sets

This would allow this script to be used for anything.

**Comment by djalmaaraujo** [comment]
@ingeniumed Thanks for this. Since react is too generic, maybe we can to vip-react-theme.json? Something like that. How you are planning to make this output file usable by other systems? Npm?

**Comment by chriszarate** [comment]
If the goal is to support modularity, can we just output every module (instead of asking the user or adding flags)?

A good model here are those "favicon generators" that output every size of favicon, along with detailed instructions, allowing the user to pick and choose what is useful to them.

**Comment by alecgeatches** [comment]
> If the goal is to support modularity, can we just output every module (instead of asking the user or adding flags)?

That would be tricky for `theme.json` - we inject into the `settings.custom` section for an existing theme file using a `--themePath` parameter. This is especially useful when testing token changes and immediately seeing the tokens update/diff in the file. We can definitely dump the intermediate result we plan to inject into the `theme.json`, but I still think we'll want to be able to specify an existing `theme.json` to match the existing behavior.

If we continue to have output-specific options like `--themePath`, does it make more sense to try to do every format at the same time? It seems like it might be better to take the opposite approach and specify a `--format` with different options based on the result.

**Comment by ingeniumed** [comment]
Just to add on to what @alecgeatches already said - it's also tricky to continue to keep it as a CLI based tool while having this flexibility for what options are available to use based on the format (react, wordpress, etc). 

> It seems like it might be better to take the opposite approach and specify a --format with different options based on the result.

I would vote for going for this. This would make the underlying code simpler as well. 

> How you are planning to make this output file usable by other systems? Npm?

Could you expand on this? We can make the location of this file flexible (the token-transformer one and the SD one) so it's widely available for use.
